name: Download Signal Dependencies

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download icmarkets mt5
        run: |
          mkdir -p deps
          curl -L "https://download.mql5.com/cdn/web/18040/mt5/icmarketssc5setup.exe" -o deps/icmarketssc5setup.exe
          ls -lh deps/

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signal-deps
          path: deps/
          retention-days: 7

